services:
  shifter_bot:
    build: .
    container_name: shifter_bot
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
        image: redis:7-alpine
        container_name: redis
        restart: always
        command: >
          redis-server 
          --appendonly yes
          -- appendfsync everysec
          -- save 60 1000
        volumes:
            - redis-data:/data

        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 3s
          retries: 5
          start_period: 5s

volumes:
    redis-data:
      driver: local
    